seed_everything: null
trainer:
  enable_checkpointing: true
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelSummary
      init_args:
        max_depth: 2
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: null
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        filename: '{epoch}-{val_light_score_epoch:.2f}'
        monitor: val_light_score_epoch
        mode: max
        verbose: true
        save_weights_only: true
        save_top_k: 20
        save_last: true
        every_n_epochs: 10
  default_root_dir: null
  gradient_clip_val: 0.5
  gradient_clip_algorithm: norm
  num_nodes: 1
  num_processes: null
  devices: null
  gpus: null
  auto_select_gpus: false
  tpu_cores: null
  ipus: null
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 10
  fast_dev_run: false
  accumulate_grad_batches: null
  max_epochs: 120
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  val_check_interval: null
  log_every_n_steps: 40
  accelerator: null
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  weights_save_path: null
  num_sanity_val_steps: 2
  resume_from_checkpoint: null
  profiler: null
  benchmark: null
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  plugins: null
  amp_backend: native
  amp_level: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
model:
  dropout: 0.0
  lr: 0.001
data:
  examples_data_dir: null
  fold: 1
  train_batch_size: 512
  val_batch_size:  512
  num_workers: 4
ckpt_path: null
